### ISSUE TITLE
GetFundamentalStock throwing an exception/error

### ISSUE THREAD

**Issue by david54321** [EodHistoricalData/EODHistoricalData.NET#11]
Error when using GetFundamentalStock on non-US stock symbols.

Examples:
var fundamentals = client.GetFundamentalStock("NOKIA.HE");
var fundamentals = client.GetFundamentalStock("STB.OL");
var fundamentals = client.GetFundamentalStock("HH.CO");

![image](https://user-images.githubusercontent.com/6160990/94985135-1608cf80-0554-11eb-97ec-8f99607877dc.png)

**Comment by david54321** [comment]
I found the fix. Make DateTimeOffset nullable :-)

![image](https://user-images.githubusercontent.com/6160990/94985405-aba55e80-0556-11eb-9072-f1374d300ab3.png)

**Comment by deios0** [comment]
Great, thanks for the solution.
