### ISSUE TITLE
How to contribute to this lib?

### ISSUE THREAD

**Issue by kavatari** [EodHistoricalData/EODHistoricalData.NET#35]
Hey @deios0 
I want to contribute to this lib and make sure that all unit tests are passing locally. But, to achieve this I need a api key - using a free one is not possible. 
Do you have any idea on this one?

**Comment by deios0** [comment]
hello, please send the request to support@eodhistoricaldata.com

**Comment by kavatari** [comment]
Thanks, send an email :) closing the issue here.
