### ISSUE TITLE
EODHistoricalData.NET cannot be referenced by a .NET Standard class library

### ISSUE THREAD

**Issue by glingt** [EodHistoricalData/EODHistoricalData.NET#5]
I want to reference EODHistoricalData.NET from another class library, that targets .NET Standard project.
Currently that is not possible since EODHistoricalData.NET is targetting .NET Core. 

See this thread
https://stackoverflow.com/questions/46087573/convert-net-core-2-0-class-libraries-to-net-standard

Retargetting EODHistoricalData.NET from .NET Core to .NET Standard would make it referencable from both .NET Framework and .NET Core apps.

The solution is to change a section in the .csproj file like this

from
```
 <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
```
to
```
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
```

I'd be happy to open a pull request that retargets the project and opening it up for both .NET Core and .NET Framework platforms.

**Comment by deios0** [comment]
Hello Nils,

Yes, thanks for the idea, it will be great if you pull the request, I will accept it. Thanks for the help with it!
