### ISSUE TITLE
Compilation throws an error: cannot convert from 'char' to 'string'

### ISSUE THREAD

**Issue by andrasfuchs** [EodHistoricalData/EODHistoricalData.NET#8]
When I try to compile the current source code, I got the following error:
`Argument 1: cannot convert from 'char' to 'string'`

The problem is at [StockPriceDataClient.cs:33](https://github.com/EodHistoricalData/EODHistoricalData.NET/blob/e81fb5a8f1c3ecb30ccd33c1be6e7818714c80d3/EODHistoricalData.NET/StockPriceDataClient.cs#L33).

**Comment by clintonrocksmith** [comment]
@andrasfuchs is this still a problem?

**Comment by andrasfuchs** [comment]
I don't know, I used the library long ago, but if you clone this repo and you can compile the source without errors, then it's definitely solved.

**Comment by clintonrocksmith** [comment]
@deios0 this can be closed
